server:
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /
  port: 8888

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cmu_edge_network?serverTimezone=Australia/Adelaide&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 1
  jackson:
    default-property-inclusion: non_null

  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 20000MB
      max-request-size: 20000MB
      enabled: true
  application:
    name: cmu-edge-network


mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  global-config:
    banner: false


logging:
  level:
    edu: debug

fast:
  upload:
    path: D:/data_upload

  generate:
    global:
      enable: false
      domainPackage: edu.domain
    dataSource:
      delOverColumn: false